spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baking?serverTimeZone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
  web:
    resources:
      static-locations: classpath:static/,file:${user.dir}/img/
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.tedu.baking: debug
knife4j:
  enable: true