spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baking?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml #??mapper????????
  configuration:
    map-underscore-to-camel-case: true #??????


logging:
  level:
    cn.tedu.baking: debug #??cn.tedu.baking???????